"""Start one of the three clients.

Offline: `--accessToken 0` is what every dev launcher passes.  Singleplayer and
LAN work; joining an online-mode server does not, which is fine -- chatwire is
tested against a local server.

Each mapping gets its own `run/` game directory so worlds, options.txt and logs
never collide, but they share one assets tree and one natives directory.
"""

from __future__ import annotations

import os
import re
import shlex
import subprocess
import sys
import threading
import time
import uuid
from pathlib import Path

from . import paths, vanilla
from .util import say

DEFAULT_USERNAME = "chatwire"
#: The line 1.8.9 prints once the window is up and the main menu is rendering.
READY_MARKERS = ("Created: 1024x512 textures-atlas", "Sound engine started")


def offline_uuid(username: str) -> str:
    """The same OfflinePlayer:<name> UUID a vanilla server derives."""
    import hashlib

    digest = bytearray(hashlib.md5(f"OfflinePlayer:{username}".encode()).digest())
    digest[6] = (digest[6] & 0x0F) | 0x30       # version 3
    digest[8] = (digest[8] & 0x3F) | 0x80       # IETF variant
    return str(uuid.UUID(bytes=bytes(digest)))


def command(mapping: str, username: str = DEFAULT_USERNAME, memory: str = "2G",
            extra_jvm: list[str] | None = None,
            extra_game: list[str] | None = None,
            join: str | None = None) -> list[str]:
    if mapping not in paths.MAPPINGS_ORDER:
        raise SystemExit(f"unknown mapping {mapping!r}; pick one of {paths.MAPPINGS_ORDER}")

    jar = paths.mapping_jar(mapping)
    if not jar.is_file():
        raise SystemExit(f"{jar} is missing -- run `python mc.py build` first")

    vj = vanilla.version_json()
    run_dir = paths.mapping_run(mapping)
    run_dir.mkdir(parents=True, exist_ok=True)

    cp = [str(p) for p in vanilla.classpath(vj)] + [str(jar)]

    jvm = [
        str(paths.java_game()),
        f"-Xmx{memory}",
        "-XX:+UseG1GC",
        "-Dfile.encoding=UTF-8",
        "-Dminecraft.mapping=" + mapping,        # so a hooked process can tell them apart
        f"-Djava.library.path={paths.NATIVES}",
        "-cp", os.pathsep.join(cp),
    ]
    jvm += extra_jvm or []

    subst = {
        "auth_player_name": username,
        "version_name": f"{paths.VERSION}-{mapping}",
        "game_directory": str(run_dir),
        "assets_root": str(paths.ASSETS),
        "assets_index_name": vj["assetIndex"]["id"],
        "auth_uuid": offline_uuid(username).replace("-", ""),
        "auth_access_token": "0",
        "user_properties": "{}",
        "user_type": "legacy",
        "auth_session": "-",
        "game_assets": str(paths.ASSETS / "virtual" / "legacy"),
    }
    template = vj.get("minecraftArguments", "")
    game_args = [
        re.sub(r"\$\{(\w+)\}", lambda m: subst.get(m.group(1), m.group(0)), tok)
        for tok in shlex.split(template)
    ]
    # `--server` / `--port` are 1.8.9's own options -- Main declares both, and
    # the launcher uses them for "join this server on launch".  They are what
    # gets a client into a world with no GUI to drive: the alternative is
    # clicking through the main menu, which no harness can do.
    if join:
        host, _, port_text = join.partition(":")
        game_args += ["--server", host, "--port", port_text or "25565"]

    game_args += extra_game or []

    return jvm + [vj["mainClass"]] + game_args


def write_script(mapping: str) -> Path:
    """A .bat that starts this mapping with no Python in the way."""
    cmd = command(mapping)
    quoted = " ".join(f'"{c}"' if (" " in c or ";" in c) else c for c in cmd)
    dest = paths.ROOT / f"launch-{mapping}.bat"
    dest.write_text(
        "@echo off\r\n"
        "rem Generated by mc.py -- re-run `python mc.py build` to refresh.\r\n"
        f'cd /d "{paths.mapping_run(mapping)}"\r\n'
        f"{quoted}\r\n",
        encoding="utf-8",
    )
    return dest


def launch(mapping: str, wait: bool = True, timeout: float | None = None,
           username: str = DEFAULT_USERNAME, memory: str = "2G",
           extra_jvm: list[str] | None = None,
           extra_game: list[str] | None = None,
           join: str | None = None):
    """Start `mapping`.  Returns its exit code, or the Popen when `wait` is false.

    The handle rather than the pid, and that is not a convenience: on Windows
    `os.kill(pid, 0)` is not a liveness probe, it is TerminateProcess.  Python
    ignores the signal number there and kills unconditionally, so the obvious
    "is it still up?" check silently shot the client it was waiting for.
    Popen.poll() is the question that asks nothing of the process.
    """
    cmd = command(mapping, username, memory, extra_jvm, extra_game, join)
    run_dir = paths.mapping_run(mapping)
    log = run_dir / "launch.log"

    say(f"* launching {mapping} ({paths.MAPPING_DESC[mapping]})")
    say(f"  game dir : {run_dir}")
    say(f"  java     : {cmd[0]}")
    say(f"  log      : {log}")

    with log.open("w", encoding="utf-8", errors="replace") as sink:
        proc = subprocess.Popen(cmd, cwd=run_dir, stdout=sink,
                                stderr=subprocess.STDOUT, text=True)
        if not wait:
            say(f"  pid      : {proc.pid}")
            return proc

        deadline = time.time() + timeout if timeout else None
        ready = False
        while proc.poll() is None:
            if not ready and log.is_file():
                text = log.read_text(encoding="utf-8", errors="replace")
                if any(m in text for m in READY_MARKERS):
                    ready = True
                    say(f"  -> {mapping} reached the main menu")
            if deadline and time.time() > deadline:
                say(f"  -> timeout, stopping {mapping}")
                proc.terminate()
                break
            time.sleep(0.5)
        proc.wait()
        return proc.returncode
